// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9E4VYQ3cnPEgMayorNCa0Wm5H3a7Tdjo',
    appId: '1:389947585177:web:435eb55986eff652efbe08',
    messagingSenderId: '389947585177',
    projectId: 'heartease-app-ebd92',
    authDomain: 'heartease-app-ebd92.firebaseapp.com',
    storageBucket: 'heartease-app-ebd92.firebasestorage.app',
    measurementId: 'G-QZ95ZWHTYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-KR5_NKxB0uUsfUaacllPY-WwbRT0ks',
    appId: '1:389947585177:android:4a2f26e90eeef1b9efbe08',
    messagingSenderId: '389947585177',
    projectId: 'heartease-app-ebd92',
    storageBucket: 'heartease-app-ebd92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHt5JTUB07AMe5IEsXAmAwFYJpJ8WYDc',
    appId: '1:389947585177:ios:61fbbd1ad1ce5aa5efbe08',
    messagingSenderId: '389947585177',
    projectId: 'heartease-app-ebd92',
    storageBucket: 'heartease-app-ebd92.firebasestorage.app',
    iosBundleId: 'com.example.hearteaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHt5JTUB07AMe5IEsXAmAwFYJpJ8WYDc',
    appId: '1:389947585177:ios:61fbbd1ad1ce5aa5efbe08',
    messagingSenderId: '389947585177',
    projectId: 'heartease-app-ebd92',
    storageBucket: 'heartease-app-ebd92.firebasestorage.app',
    iosBundleId: 'com.example.hearteaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9E4VYQ3cnPEgMayorNCa0Wm5H3a7Tdjo',
    appId: '1:389947585177:web:c922280251b23067efbe08',
    messagingSenderId: '389947585177',
    projectId: 'heartease-app-ebd92',
    authDomain: 'heartease-app-ebd92.firebaseapp.com',
    storageBucket: 'heartease-app-ebd92.firebasestorage.app',
    measurementId: 'G-0Q1T5375NP',
  );
}
